name: Coverage
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      # this moves to the directory of dotting!
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Install dependencies
        run: yarn

      - name: Test and coverage
        run: yarn test --coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage/lcov.info
