# .github/workflows/preview.yml
name: Deploy PR previews

# on:
#   pull_request:
#     types:
#       - opened
#       - reopened
#       - synchronize
#       - closed

on:
  workflow_run:
    workflows: ["Coverage"]
    types:
      - completed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          yarn install
          yarn run storybook:build

      - name: Download PR number artifact
        uses: actions/download-artifact@v2
        with:
          name: pr-number

      - name: Read PR number
        id: pr
        run: echo "::set-output name=number::$(cat pr_number.txt)"

      - name: Use PR Number
        run: |
          echo "The PR number is ${{ steps.pr.outputs.number }}"

      - name: Set PR Number as pr=$pr
        run: echo "pr=${{ steps.pr.outputs.number }}" >> $GITHUB_ENV

      - name: Deploy preview
        id: deploy-preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./storybook-static/
          preview-branch: preview
          custom-url: dotting-preview.netlify.app
          # umbrella-dir: docs/pr-preview
          token: ${{ secrets.GITHUB_TOKEN }}
          action: deploy # This prevents netlify from auto deleting url


      # - name: Post PR comment
      #   uses: actions/github-script@v5
      #   with:
      #     script: |
      #       const url = "${{ steps.deploy-preview.outputs.url }}";
      #       if (url) {
      #         github.rest.issues.createComment({
      #           owner: context.repo.owner,
      #           repo: context.repo.repo,
      #           issue_number: context.issue.number,
      #           body: `Preview URL: ${url}`
      #         });
      #       } else {
      #         core.setFailed('No preview URL found');
      #       }
      #       const prNumber = context.payload.workflow_run.pull_requests[0].number;
      #       const previewURL = 'https://dotting-preview.netlify.app'; // Adjust based on actual preview URL logic
      #       github.rest.issues.createComment({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         issue_number: prNumber,
      #         body: `Preview URL: ${previewURL}`
      #       });
